version: 2.1

jobs:
  deploy:
    docker: 
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:kNGn/e0qgg7j4sxEAqkbDsvztMAmzcBng/hziY0jfDg"
      - run:
          name: Run deploy script
          command: bash ~/project/scripts/deploy.sh

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main