version: 2.1

jobs:
  deploy:
    docker: 
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "fd:3a:bf:ab:6c:ea:c3:95:27:74:86:c2:96:41:da:da"
      - run:
          name: Run deploy script
          command: bash ~/project/scripts/deploy.sh

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main